doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '8.0'

        types:
            config_value: App\Config\Infrastructure\Persistence\Doctrine\Type\ConfigValueType
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false
                mappings:
                    RefreshToken:
                        type: xml
                        dir: '%kernel.project_dir%/vendor/gesdinet/jwt-refresh-token-bundle/Resources/config/doctrine'
                        prefix: 'Gesdinet\JWTRefreshTokenBundle\Entity'
                    Task:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Task/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'App\Task\Domain\Entity'
                        alias: Task
                    User:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/User/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'App\User\Domain\Entity'
                        alias: User
                    Project:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Project/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'App\Project\Domain\Entity'
                        alias: Project
                    Comment:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Comment/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'App\Comment\Domain\Entity'
                        alias: Comment
                    Config:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Config/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'App\Config\Domain\Entity'
                        alias: Config
