App\Comment\Domain\Entity\Comment:
    attributes:
        id:
            groups: ['comment:read']
        content:
            groups: ['comment:read', 'comment:write']
        authorId:
            groups: ['comment:read']
        taskId:
            groups: ['comment:read']
        createdAt:
            groups: ['comment:read']
        updatedAt:
            groups: ['comment:read']