App\Project\Domain\Entity\Project:
    attributes:
        id:
            groups: ['project:read']
        title:
            groups: ['project:read', 'project:write']
        description:
            groups: ['project:read', 'project:write']
        ownerId:
            groups: ['project:read']
        createdAt:
            groups: ['project:read']
        updatedAt:
            groups: ['project:read']