App\Task\Domain\Entity\Task:
    attributes:
        id:
            groups: ['task:read']
        title:
            groups: ['task:read', 'task:write']
        description:
            groups: ['task:read', 'task:write']
        status:
            groups: ['task:read', 'task:write']
        type:
            groups: ['task:read', 'task:write']
        priority:
            groups: ['task:read', 'task:write']
        ownerId:
            groups: ['task:read']
        parentId:
            groups: ['task:read']
        projectId:
            groups: ['task:read']
        createdAt:
            groups: ['task:read']
        updatedAt:
            groups: ['task:read']
